object Versions {

    const val CORE_KTX = "1.15.0"
    const val APPCOMPAT = "1.7.0"
    const val MATERIAL = "1.12.0"
    const val COMPOSE = "1.7.5"
    const val MATERIAL3 = "1.3.1"
    const val ACTIVITY_COMPOSE = "1.9.3"
    const val LIFECYCLE = "2.8.7"
    const val NAVIGATION = "2.8.4"
    const val ACCOMPANIST_INSETS = "0.23.1"
    const val ACCOMPANIST_NAV_ANIMATION = "0.24.10-beta"
    const val ACCOMPANIST_PAGER = "0.23.1"
    const val CONSTRAINT_LAYOUT = "1.1.0"
    const val COROUTINES_ANDROID = "1.7.3"
    const val COROUTINES_CORE = "1.6.4"
    const val ROOM = "2.6.1"
    const val HILT = "2.49"
    const val HILT_NAVIGATION_COMPOSE = "1.2.0"
    const val RETROFIT = "2.9.0"
    const val MOSHI = "1.14.0"
    const val OKHTTP = "4.11.0"
    const val COIL = "2.2.2"
    const val PAGING = "3.3.4"
    const val DATASTORE = "1.1.1"
    const val PROTOBUF = "3.21.7"
    const val LOTTIE = "6.0.0"
    const val MEDIA3 = "1.5.0"
    const val CHUCKER = "4.0.0"
    const val WORK = "2.10.0"
    const val JUNIT = "4.13.2"
    const val HAMCREST = "1.3"
    const val ARCH_CORE_TESTING = "1.1.1"
    const val MOCKITO = "3.9.0"
    const val MOCKITO_ANDROID = "3.4.6"
    const val MOCKK = "1.13.2"
    const val TURBINE = "1.0.0"
    const val ANDROID_JUNIT = "1.2.1"
    const val ESPRESSO = "3.6.1"
    const val ANDROID_TEST_CORE = "1.6.1"
    const val COROUTINES_TEST = "1.6.4"

}